### PR TITLE
Linter fixes

### PR DESCRIPTION
**Pull request by juanpcapurro**
Please consider configuring github merge to do a linear/semi-linear history on merge preserving history so:

- when reading a blame/log, automated linter changes can be told apart from ones made by hoomans
- contributor credit is registered in git history as well as github repository

### CODE REVIEW

**Comment by juanpcapurro** [comment]
@dbale-altoros can i haz approval for workflow so I know if I have something to fix?

**Comment by dbale-altoros** [comment]
@juanpcapurro 
I did almost the exact pr with linter fixes and some minor modification in order the tests to pass...
So this one will not be merged, I already reviewed mine, so there's no point to go through all these changes

**Comment by juanpcapurro** [comment]
@dbale-altoros this PR is rebased on top of current master and ready for review again ✨

**Review by dbale-altoros — APPROVED** [review]

**Comment by dbale-altoros** [comment]
> @dbale-altoros this PR is rebased on top of current master and ready for review again sparkles

GREAT! Thanks

**Pull request merged**
