### PR TITLE
[ New Rule ] No unused imports

### PR DESCRIPTION
**Pull request by juanpcapurro**
I've modified both [openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) and [exactly](https://github.com/exactly/protocol) to manually add this rule and check for false positives, couldn't find any in the current implementation. However, I'm concerned I might be forgetting to register some usage regarding inline assembly or some other less-used feature, so feedback is of course appreciated on that.

as always, see git history for details.

### CODE REVIEW

**Comment by dbale-altoros** [comment]
@juanpcapurro This is a cool rule! Thanks for that.
This is marked as draft... not sure if it's not finished yet, or you put it that way because it depends on the previous PR

**Comment by juanpcapurro** [comment]
> @juanpcapurro This is a cool rule! Thanks for that. This is marked as draft... not sure if it's not finished yet, or you put it that way because it depends on the previous PR

Hi Diego, this PR is not in a mergable state sadly, since it still has many false positives yet. so far I've found the implementation errors out when an imported name is used as:

- [ ] type for
    - [ ] variable inside a function
    - [ ] struct definition
- [ ] value for
    - [ ] revert statement
    - [ ] accessing one if its members

and also has the following errors:

- [ ] reports original name when aliased name is not used

so a full review isn't in order yet. However, I'd of course greatly appreciate feedback on how I'm approaching the fix, if I'm organizing the code right, those kinds of things.

Small chores, such as not repeating myself for the different errors that have the same message, I'll probably fix later when I have the entire feature figured out though.

**Comment by dbale-altoros** [comment]
Ok, no worries... You made such great contributions here... I cannot say other thing than thank you.
I don't know how much time I will be given to approach next tasks on solhint... as soon as I have some spare time I'll try to give you some feedback (if any)

**Comment by juanpcapurro** [comment]
@fvictorio @dbale-altoros  :sparkles: should be ready for review now :sparkles:

**Review by dbale-altoros — APPROVED** [review]
I tested it and seems pretty tight
@fvictorio what do you think ?

**Comment by juanpcapurro** [comment]
> Great to see this rule being added, any idea on when the next release will be?

This rule is already released in [solhint-community](https://github.com/solhint-community/solhint-community/) 3.5.1, where a few devs and myself are continuing development

**Comment by dbale-altoros** [comment]
@juanpcapurro Como estas ?
Te consulto algo.
Veo que esta regla asi como esta codeada tiene varios falsos positivos que fueron arreglados en la version de community
Te molestaria si tomo los fixes de ese repo para esta regla asi la dejamos bien aca tambien ? 

Gracias y disculpa la molestia

**Comment by dbale-altoros** [comment]
@dbale-altoros check

**Pull request merged**
