### PR TITLE
Fix e2e tests

### PR DESCRIPTION
**Pull request by juanpcapurro**
see commit history for details. Main feedback items are:

- ~is it okay to drop the table formatter?~ didn't drop it
- should I backport the formatters' tests into this codebase? -- discussion deferred to: #386

### CODE REVIEW

**Comment by juanpcapurro** [comment]
I'll get the table formatter back and remove the draft status. I realized that dropping it would involve a minor or perhaps even major version bump, which would prevent users getting the semver-compatible version from having the updated dependencies, and even if there's a bug in a formatter, it wouldn't have dire consequences.

**Comment by fvictorio** [comment]
Great work @juanpcapurro!

@frangio is the attribution here enough?

**Comment by dbale-altoros** [comment]
@juanpcapurro this is great!
Thanks for the contribution
As I remember in previous PR there was a discussion where to not lock the dependencies version and add the ^ in the package json to the ones previously had
I am in favor of that, considering what @frangio comment

@fvictorio are you agree ?
@juanpcapurro can you add those ?

**Comment by fvictorio** [comment]
> As I remember in previous PR there was a discussion where to not lock the dependencies version and add the ^ in the package json to the ones previously had

Good catch. Yeah, we should do that here too.

**Comment by frangio** [comment]
I would take the [`LICENSE`](https://github.com/eslint/eslint/blob/d8c8ede088e1f4a82c9b6b5c2772af268b9161aa/LICENSE) file from ESLint and put it in the formatters directory. Perhaps additionally a readme file in the same directory saying where the code was vendored from. That should do it.

**Comment by dbale-altoros** [comment]
@juanpcapurro do you want to finish it yourself ? (adding the ^ and what frangio said) 
Or should I continue it ?

cheers! great job

**Comment by juanpcapurro** [comment]
> do you want to finish it yourself ? (adding the ^ and what frangio said)
Or should I continue it ?

I meant to do the semver-range dependencies in a separate PR and also take care of the dependencies for the package.json in the e2e directory, but there seems to be consensus to include them here so I will

I'll implement the suggested feedback sometime today or tomorrow

**Comment by dbale-altoros** [comment]
> > do you want to finish it yourself ? (adding the ^ and what frangio said)
> > Or should I continue it ?
> 
> I meant to do the semver-range dependencies in a separate PR and also take care of the dependencies for the package.json in the e2e directory, but there seems to be consensus to include them here so I will
> 
> I'll implement the suggested feedback sometime today or tomorrow

excellent!! thanks for your contribution

**Comment by juanpcapurro** [comment]
all feedback items should be addressed now. I took the liberty of changing the node version against which the CI is run to the two oldest supported versions (14,16) instead of 10 and 12, which had both reached end of life

**Comment by dbale-altoros** [comment]
> all feedback items should be addressed now. I took the liberty of changing the node version against which the CI is run to the two oldest supported versions (14,16) instead of 10 and 12, which had both reached end of life

this is great... I approved the PR
@fvictorio 
@frangio 
Do you guys have something to add ?

**Review by dbale-altoros — APPROVED** [review]

**Comment by frangio** [comment]
Looks good to me! Thank you!

**Comment by frangio** [comment]
Do you plan to release this soon?

**Comment by dbale-altoros** [comment]
I will discuss it with Franco... we are addressing some of the issues in the repo

**Pull request merged**
