### PR TITLE
fix maxWarnings when multiple reports

### LINKED ISSUE #159: maxWarnings flag doesn't work as expected when there are multiple source files
When calculating if the number of warnings exceeds the number given by the maxWarnings flag, only the first source file (report) is taken into account. Any warnings in subsequent files are not counted.

### PR DESCRIPTION
**Pull request by kevsul**
Fixes #159

### CODE REVIEW

**Comment by fvictorio** [comment]
Wow, huge bug. Thanks @kevsul! Could you please run prettier so that the CI passes?

**Comment by pablofullana** [comment]
Looks like something that could have been caught by a test taking into multiple reports into account. @fvictorio can we plan on adding this scenario?

**Comment by kevsul** [comment]
> Wow, huge bug. Thanks @kevsul! Could you please run prettier so that the CI passes?

Done.

**Comment by fvictorio** [comment]
Thanks @kevsul!

@pablofullana: I opened https://github.com/protofire/solhint/issues/161 to track this.

**Pull request merged**
