### PR TITLE
allow more flexible fixer utilizing current src

### PR DESCRIPTION
**Pull request by shir0u**
I'm trying to create a fixer for ordering rule, but cannot do that without referencing the current source.

### CODE REVIEW

**Comment by dbale-altoros** [comment]
> I'm trying to create a fixer for ordering rule, but cannot do that without referencing the current source.

Can you give more context to this @shir0u  ? 
This project is gonna be supported soon

**Comment by shirotech** [comment]
> > I'm trying to create a fixer for ordering rule, but cannot do that without referencing the current source.
> 
> Can you give more context to this @shir0u ? This project is gonna be supported soon

It just gives reference to original source to deal with context around reporting and fixing. One example is creating a plugin that can order/sort things, and to do that we need to know the whole original source.

**Comment by shir0u** [comment]
> > I'm trying to create a fixer for ordering rule, but cannot do that without referencing the current source.
> 
> Can you give more context to this @shir0u ? This project is gonna be supported soon

It just gives reference to original source to deal with context around reporting and fixing. One example is creating a plugin that can order/sort things, and to do that we need to know the whole original source.

**Review by pfmescher — APPROVED** [review]
This seems harmless.. maybe it will increase memory usage a bit but otherwise I don't see why we wouldn't allow this.

**Comment by fvictorio** [comment]
@shir0u the constructor of a rule receives the input source as a third parameter. So you can do this:

```
class MyRule extends BaseChecker {
  constructor(reporter, config, inputSrc) {
    super(reporter, ruleId, meta)
    this.inputSrc = inputSrc
  }
```

and then use `this.inputSrc` in your fixer (assuming it's an arrow function).

I'm not against adding this, but it seems unnecessary given that that workaround exists.

**Comment by shirotech** [comment]
> @shir0u the constructor of a rule receives the input source as a third parameter. So you can do this:
> 
> ```
> class MyRule extends BaseChecker {
>   constructor(reporter, config, inputSrc) {
>     super(reporter, ruleId, meta)
>     this.inputSrc = inputSrc
>   }
> ```
> 
> and then use `this.inputSrc` in your fixer (assuming it's an arrow function).
> 
> I'm not against adding this, but it seems unnecessary given that that workaround exists.

Where are you getting these signatures from? It looks very different to https://github.com/protofire/solhint/blob/master/lib/rules/base-checker.js#L23

**Comment by shir0u** [comment]
> @shir0u the constructor of a rule receives the input source as a third parameter. So you can do this:
> 
> ```
> class MyRule extends BaseChecker {
>   constructor(reporter, config, inputSrc) {
>     super(reporter, ruleId, meta)
>     this.inputSrc = inputSrc
>   }
> ```
> 
> and then use `this.inputSrc` in your fixer (assuming it's an arrow function).
> 
> I'm not against adding this, but it seems unnecessary given that that workaround exists.

Where are you getting these signatures from? It looks very different to https://github.com/protofire/solhint/blob/master/lib/rules/base-checker.js#L23

**Comment by dbale-altoros** [comment]
@fvictorio so what's the status of this ?
Seems it can be dismissed ?

**Comment by shir0u** [comment]
I think this can be closed, thank you all for your inputs.

**Pull request closed without merging**
